mybatis:
  type-aliases-package: com.github.JiangGuangxing.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.github.JiangGuangxing.core.BaseMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/nxin_price2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver

