CREATE TABLE `country` (
  `Id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `countryname` varchar(255) DEFAULT NULL COMMENT '名称',
  `countrycode` varchar(255) DEFAULT NULL COMMENT '代码',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='国家信息';

insert into `country` (`countryname`, `countrycode`) values('Antigua and Barbuda','AG');
insert into `country` (`countryname`, `countrycode`) values('Argentina','AR');
insert into `country` (`countryname`, `countrycode`) values('Armenia','AM');
insert into `country` (`countryname`, `countrycode`) values('Australia','AU');
insert into `country` (`countryname`, `countrycode`) values('Austria','AT');
insert into `country` (`countryname`, `countrycode`) values('Azerbaijan','AZ');
insert into `country` (`countryname`, `countrycode`) values('Bahamas','BS');
insert into `country` (`countryname`, `countrycode`) values('Bahrain','BH');
insert into `country` (`countryname`, `countrycode`) values('Bangladesh','BD');
insert into `country` (`countryname`, `countrycode`) values('Barbados','BB');
insert into `country` (`countryname`, `countrycode`) values('Belarus','BY');
insert into `country` (`countryname`, `countrycode`) values('Belgium','BE');
insert into `country` (`countryname`, `countrycode`) values('Belize','BZ');
insert into `country` (`countryname`, `countrycode`) values('Benin','BJ');
insert into `country` (`countryname`, `countrycode`) values('Bermuda Is.','BM');
insert into `country` (`countryname`, `countrycode`) values('Bolivia','BO');
insert into `country` (`countryname`, `countrycode`) values('Botswana','BW');
insert into `country` (`countryname`, `countrycode`) values('Brazil','BR');
insert into `country` (`countryname`, `countrycode`) values('Brunei','BN');
insert into `country` (`countryname`, `countrycode`) values('Bulgaria','BG');
insert into `country` (`countryname`, `countrycode`) values('Burkina-faso','BF');
insert into `country` (`countryname`, `countrycode`) values('Burma','MM');
insert into `country` (`countryname`, `countrycode`) values('Burundi','BI');
insert into `country` (`countryname`, `countrycode`) values('Cameroon','CM');
insert into `country` (`countryname`, `countrycode`) values('Canada','CA');
insert into `country` (`countryname`, `countrycode`) values('Central African Republic','CF');
insert into `country` (`countryname`, `countrycode`) values('Chad','TD');
insert into `country` (`countryname`, `countrycode`) values('Chile','CL');
insert into `country` (`countryname`, `countrycode`) values('China','CN');
insert into `country` (`countryname`, `countrycode`) values('Colombia','CO');
insert into `country` (`countryname`, `countrycode`) values('Congo','CG');
insert into `country` (`countryname`, `countrycode`) values('Cook Is.','CK');
insert into `country` (`countryname`, `countrycode`) values('Costa Rica','CR');
insert into `country` (`countryname`, `countrycode`) values('Cuba','CU');
insert into `country` (`countryname`, `countrycode`) values('Cyprus2','CY');
insert into `country` (`countryname`, `countrycode`) values('Czech Republic','CZ');
insert into `country` (`countryname`, `countrycode`) values('Denmark','DK');
insert into `country` (`countryname`, `countrycode`) values('Djibouti','DJ');
insert into `country` (`countryname`, `countrycode`) values('Dominica Rep.','DO');
insert into `country` (`countryname`, `countrycode`) values('Ecuador','EC');
insert into `country` (`countryname`, `countrycode`) values('Egypt','EG');
insert into `country` (`countryname`, `countrycode`) values('EI Salvador','SV');
insert into `country` (`countryname`, `countrycode`) values('Estonia','EE');
insert into `country` (`countryname`, `countrycode`) values('Ethiopia','ET');
insert into `country` (`countryname`, `countrycode`) values('Fiji','FJ');
insert into `country` (`countryname`, `countrycode`) values('France','FR');
insert into `country` (`countryname`, `countrycode`) values('French Guiana','GF');
insert into `country` (`countryname`, `countrycode`) values('Gabon','GA');
insert into `country` (`countryname`, `countrycode`) values('Gambia','GM');
insert into `country` (`countryname`, `countrycode`) values('Georgia','GE');
insert into `country` (`countryname`, `countrycode`) values('Germany','DE');
insert into `country` (`countryname`, `countrycode`) values('Ghana','GH');
insert into `country` (`countryname`, `countrycode`) values('Gibraltar','GI');
insert into `country` (`countryname`, `countrycode`) values('Greece','GR');
insert into `country` (`countryname`, `countrycode`) values('Grenada','GD');
insert into `country` (`countryname`, `countrycode`) values('Guam','GU');
insert into `country` (`countryname`, `countrycode`) values('Guatemala','GT');
insert into `country` (`countryname`, `countrycode`) values('Guinea','GN');
insert into `country` (`countryname`, `countrycode`) values('Guyana','GY');
insert into `country` (`countryname`, `countrycode`) values('Haiti','HT');
insert into `country` (`countryname`, `countrycode`) values('Honduras','HN');
insert into `country` (`countryname`, `countrycode`) values('Hongkong','HK');
insert into `country` (`countryname`, `countrycode`) values('Hungary','HU');
insert into `country` (`countryname`, `countrycode`) values('Iceland','IS');
insert into `country` (`countryname`, `countrycode`) values('India','IN');
insert into `country` (`countryname`, `countrycode`) values('Indonesia','ID');
insert into `country` (`countryname`, `countrycode`) values('Iran','IR');
insert into `country` (`countryname`, `countrycode`) values('Iraq','IQ');
insert into `country` (`countryname`, `countrycode`) values('Ireland','IE');
insert into `country` (`countryname`, `countrycode`) values('Israel','IL');
insert into `country` (`countryname`, `countrycode`) values('Italy','IT');
insert into `country` (`countryname`, `countrycode`) values('Jamaica','JM');
insert into `country` (`countryname`, `countrycode`) values('Japan','JP');
insert into `country` (`countryname`, `countrycode`) values('Jordan','JO');
insert into `country` (`countryname`, `countrycode`) values('Kampuchea (Cambodia )','KH');
insert into `country` (`countryname`, `countrycode`) values('Kazakstan','KZ');
insert into `country` (`countryname`, `countrycode`) values('Kenya','KE');
insert into `country` (`countryname`, `countrycode`) values('Korea','KR');
insert into `country` (`countryname`, `countrycode`) values('Kuwait','KW');
insert into `country` (`countryname`, `countrycode`) values('Kyrgyzstan','KG');
insert into `country` (`countryname`, `countrycode`) values('Laos','LA');
insert into `country` (`countryname`, `countrycode`) values('Latvia','LV');
insert into `country` (`countryname`, `countrycode`) values('Lebanon','LB');
insert into `country` (`countryname`, `countrycode`) values('Lesotho','LS');
insert into `country` (`countryname`, `countrycode`) values('Liberia','LR');
insert into `country` (`countryname`, `countrycode`) values('Libya','LY');
insert into `country` (`countryname`, `countrycode`) values('Liechtenstein','LI');
insert into `country` (`countryname`, `countrycode`) values('Lithuania','LT');
insert into `country` (`countryname`, `countrycode`) values('Luxembourg','LU');
insert into `country` (`countryname`, `countrycode`) values('Macao','MO');
insert into `country` (`countryname`, `countrycode`) values('Madagascar','MG');
insert into `country` (`countryname`, `countrycode`) values('Malawi','MW');
insert into `country` (`countryname`, `countrycode`) values('Malaysia','MY');
insert into `country` (`countryname`, `countrycode`) values('Maldives','MV');
insert into `country` (`countryname`, `countrycode`) values('Mali','ML');
insert into `country` (`countryname`, `countrycode`) values('Malta','MT');
insert into `country` (`countryname`, `countrycode`) values('Mauritius','MU');
insert into `country` (`countryname`, `countrycode`) values('Mexico','MX');
insert into `country` (`countryname`, `countrycode`) values('Moldova, Republic of','MD');
insert into `country` (`countryname`, `countrycode`) values('Monaco','MC');
insert into `country` (`countryname`, `countrycode`) values('Mongolia','MN');
insert into `country` (`countryname`, `countrycode`) values('Montserrat Is','MS');
insert into `country` (`countryname`, `countrycode`) values('Morocco','MA');
insert into `country` (`countryname`, `countrycode`) values('Mozambique','MZ');
insert into `country` (`countryname`, `countrycode`) values('Namibia','NA');
insert into `country` (`countryname`, `countrycode`) values('Nauru','NR');
insert into `country` (`countryname`, `countrycode`) values('Nepal','NP');
insert into `country` (`countryname`, `countrycode`) values('Netherlands','NL');
insert into `country` (`countryname`, `countrycode`) values('New Zealand','NZ');
insert into `country` (`countryname`, `countrycode`) values('Nicaragua','NI');
insert into `country` (`countryname`, `countrycode`) values('Niger','NE');
insert into `country` (`countryname`, `countrycode`) values('Nigeria','NG');
insert into `country` (`countryname`, `countrycode`) values('North Korea','KP');
insert into `country` (`countryname`, `countrycode`) values('Norway','NO');
insert into `country` (`countryname`, `countrycode`) values('Oman','OM');
insert into `country` (`countryname`, `countrycode`) values('Pakistan','PK');
insert into `country` (`countryname`, `countrycode`) values('Panama','PA');
insert into `country` (`countryname`, `countrycode`) values('Papua New Cuinea','PG');
insert into `country` (`countryname`, `countrycode`) values('Paraguay','PY');
insert into `country` (`countryname`, `countrycode`) values('Peru','PE');
insert into `country` (`countryname`, `countrycode`) values('Philippines','PH');
insert into `country` (`countryname`, `countrycode`) values('Poland','PL');
insert into `country` (`countryname`, `countrycode`) values('French Polynesia','PF');
insert into `country` (`countryname`, `countrycode`) values('Portugal','PT');
insert into `country` (`countryname`, `countrycode`) values('Puerto Rico','PR');
insert into `country` (`countryname`, `countrycode`) values('Qatar','QA');
insert into `country` (`countryname`, `countrycode`) values('Romania','RO');
insert into `country` (`countryname`, `countrycode`) values('Russia','RU');
insert into `country` (`countryname`, `countrycode`) values('Saint Lueia','LC');
insert into `country` (`countryname`, `countrycode`) values('Saint Vincent','VC');
insert into `country` (`countryname`, `countrycode`) values('San Marino','SM');
insert into `country` (`countryname`, `countrycode`) values('Sao Tome and Principe','ST');
insert into `country` (`countryname`, `countrycode`) values('Saudi Arabia','SA');
insert into `country` (`countryname`, `countrycode`) values('Senegal','SN');
insert into `country` (`countryname`, `countrycode`) values('Seychelles','SC');
insert into `country` (`countryname`, `countrycode`) values('Sierra Leone','SL');
insert into `country` (`countryname`, `countrycode`) values('Singapore','SG');
insert into `country` (`countryname`, `countrycode`) values('Slovakia','SK');
insert into `country` (`countryname`, `countrycode`) values('Slovenia','SI');
insert into `country` (`countryname`, `countrycode`) values('Solomon Is','SB');
insert into `country` (`countryname`, `countrycode`) values('Somali','SO');
insert into `country` (`countryname`, `countrycode`) values('South Africa','ZA');
insert into `country` (`countryname`, `countrycode`) values('Spain','ES');
insert into `country` (`countryname`, `countrycode`) values('Sri Lanka','LK');
insert into `country` (`countryname`, `countrycode`) values('St.Lucia','LC');
insert into `country` (`countryname`, `countrycode`) values('St.Vincent','VC');
insert into `country` (`countryname`, `countrycode`) values('Sudan','SD');
insert into `country` (`countryname`, `countrycode`) values('Suriname','SR');
insert into `country` (`countryname`, `countrycode`) values('Swaziland','SZ');
insert into `country` (`countryname`, `countrycode`) values('Sweden','SE');
insert into `country` (`countryname`, `countrycode`) values('Switzerland','CH');
insert into `country` (`countryname`, `countrycode`) values('Syria','SY');
insert into `country` (`countryname`, `countrycode`) values('Taiwan','TW');
insert into `country` (`countryname`, `countrycode`) values('Tajikstan','TJ');
insert into `country` (`countryname`, `countrycode`) values('Tanzania','TZ');
insert into `country` (`countryname`, `countrycode`) values('Thailand','TH');
insert into `country` (`countryname`, `countrycode`) values('Togo','TG');
insert into `country` (`countryname`, `countrycode`) values('Tonga','TO');
insert into `country` (`countryname`, `countrycode`) values('Trinidad and Tobago','TT');
insert into `country` (`countryname`, `countrycode`) values('Tunisia','TN');
insert into `country` (`countryname`, `countrycode`) values('Turkey','TR');
insert into `country` (`countryname`, `countrycode`) values('Turkmenistan','TM');
insert into `country` (`countryname`, `countrycode`) values('Uganda','UG');
insert into `country` (`countryname`, `countrycode`) values('Ukraine','UA');
insert into `country` (`countryname`, `countrycode`) values('United Arab Emirates','AE');
insert into `country` (`countryname`, `countrycode`) values('United Kiongdom','GB');
insert into `country` (`countryname`, `countrycode`) values('United States of America','US');
insert into `country` (`countryname`, `countrycode`) values('Uruguay','UY');
insert into `country` (`countryname`, `countrycode`) values('Uzbekistan','UZ');
insert into `country` (`countryname`, `countrycode`) values('Venezuela','VE');
insert into `country` (`countryname`, `countrycode`) values('Vietnam','VN');
insert into `country` (`countryname`, `countrycode`) values('Yemen','YE');
insert into `country` (`countryname`, `countrycode`) values('Yugoslavia','YU');
insert into `country` (`countryname`, `countrycode`) values('Zimbabwe','ZW');
insert into `country` (`countryname`, `countrycode`) values('Zaire','ZR');
insert into `country` (`countryname`, `countrycode`) values('Zambia','ZM');


